version: '3.8'

services:
  # --- API GATEWAY ---
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - MATERIA_SERVICE_URL=http://materia-service:8002
      - ADVISOR_SERVICE_URL=http://advisor-service:8003
      - REVIEW_SERVICE_URL=http://review-service:8004
      - CALENDAR_SERVICE_URL=http://calendar-service:8007
    # Eliminamos depends_on para evitar que el fallo de uno detenga al Gateway

  # --- MICROSERVICIOS ---

  auth-service:
    build: ./auth-service
    container_name: auth-service
    expose:
      - "8001"
    environment:
      - DATABASE_URL=mysql+pymysql://admin:contrasena12345@db-sistema.cvjyu96ahzvc.us-east-1.rds.amazonaws.com:3306/asesorias
      - JWT_SECRET=Taller2026

  advisor-service:
    build: ./advisor-service
    container_name: advisor-service
    expose:
      - "8003"
    environment:
      - DATABASE_URL=mysql+pymysql://admin:contrasena12345@db-sistema.cvjyu96ahzvc.us-east-1.rds.amazonaws.com:3306/asesor_db

  calendar-service:
    build: ./calendar-service
    container_name: calendar-service
    expose:
      - "8007"
    environment:
      - DATABASE_URL=mysql+pymysql://admin:contrasena12345@db-sistema.cvjyu96ahzvc.us-east-1.rds.amazonaws.com:3306/asesor_db

  materia-service:
    build: ./materia-service
    container_name: materia-service
    expose:
      - "8002"
    environment:
      - DATABASE_URL=mysql+pymysql://admin:contrasena12345@db-sistema.cvjyu96ahzvc.us-east-1.rds.amazonaws.com:3306/BD_materias

  review-service:
    build: ./review-service
    container_name: review-service
    expose:
      - "8004"
    environment:
      - DATABASE_URL=mysql+pymysql://admin:contrasena12345@db-sistema.cvjyu96ahzvc.us-east-1.rds.amazonaws.com:3306/resenas_db