services:
  mysql-db:
    image: mysql:8.0
    container_name: admin-devmentor-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: